package io.github.mkckr0.audio_share_app.model

// Generated by scripts/initialize-updater-key.ps1. The private key is not stored in the repository.
object UpdatePublicKey {
    const val SPKI_BASE64 = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEZZWUGfzNTcLm6Qi4Zt8PyUsfAccs6ogWwtop7+0TKASJHBZ+a0dXdXLgaXKlXrcnBhEFPlhswnTLoBl9gCYIbg=="
}
