[CmdletBinding(SupportsShouldProcess)]
param(
    [string]$PrivateKeyPath = "",
    [switch]$Force
)

if ($PSVersionTable.PSVersion.Major -lt 7) {
    $pwshCommand = Get-Command pwsh.exe -ErrorAction SilentlyContinue
    $pwshCandidates = @(
        $(if ($pwshCommand) { $pwshCommand.Source }),
        (Join-Path $env:ProgramFiles "PowerShell\7\pwsh.exe"),
        (Join-Path $env:LOCALAPPDATA "Microsoft\WindowsApps\pwsh.exe")
    ) | Where-Object { $_ -and (Test-Path -LiteralPath $_ -PathType Leaf) }
    $pwsh = $pwshCandidates | Select-Object -First 1
    if (-not $pwsh) {
        throw "PowerShell 7 or later is required. Install it with 'winget install --id Microsoft.PowerShell --source winget', reopen the terminal, then run this command again."
    }

    $forwardedArguments = @("-NoLogo", "-NoProfile", "-ExecutionPolicy", "Bypass", "-File", $PSCommandPath)
    if (-not [string]::IsNullOrWhiteSpace($PrivateKeyPath)) {
        $forwardedArguments += @("-PrivateKeyPath", $PrivateKeyPath)
    }
    if ($Force) {
        $forwardedArguments += "-Force"
    }
    if ($WhatIfPreference) {
        $forwardedArguments += "-WhatIf"
    }
    & $pwsh @forwardedArguments
    exit $LASTEXITCODE
}

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$projectRoot = Split-Path -Parent $PSScriptRoot
$settingsPath = Join-Path $projectRoot "settings\updater.json"
$publicHeaderPath = Join-Path $projectRoot "server-mfc\updater-common\update_public_key.hpp"
$androidPublicKeyPath = Join-Path $projectRoot "android-app\app\src\main\java\io\github\mkckr0\audio_share_app\model\UpdatePublicKey.kt"

if ([string]::IsNullOrWhiteSpace($PrivateKeyPath)) {
    if (-not (Test-Path -LiteralPath $settingsPath -PathType Leaf)) {
        throw "Provide -PrivateKeyPath or create settings/updater.json from settings/updater.example.json."
    }
    $settings = Get-Content -LiteralPath $settingsPath -Raw -Encoding UTF8 | ConvertFrom-Json
    $PrivateKeyPath = [string]$settings.privateKeyPath
}
if ([string]::IsNullOrWhiteSpace($PrivateKeyPath)) {
    throw "The updater private key path is empty."
}

$resolvedKeyPath = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($PrivateKeyPath)
if ((Test-Path -LiteralPath $resolvedKeyPath) -and -not $Force) {
    throw "The private key already exists. Refusing to replace it without -Force: $resolvedKeyPath"
}
if (-not $PSCmdlet.ShouldProcess($resolvedKeyPath, "Generate a password-encrypted ECDSA P-256 updater key")) {
    return
}

$password = Read-Host "Enter a new updater private-key password" -AsSecureString
$confirmation = Read-Host "Enter the password again" -AsSecureString
$passwordPointer = [IntPtr]::Zero
$confirmationPointer = [IntPtr]::Zero
$plainPassword = $null
$plainConfirmation = $null
$ecdsa = $null

try {
    $passwordPointer = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($password)
    $confirmationPointer = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($confirmation)
    $plainPassword = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($passwordPointer)
    $plainConfirmation = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($confirmationPointer)
    if ([string]::IsNullOrWhiteSpace($plainPassword) -or $plainPassword.Length -lt 12) {
        throw "The private-key password must contain at least 12 characters."
    }
    if ($plainPassword -cne $plainConfirmation) {
        throw "The private-key passwords do not match."
    }

    $curve = [Security.Cryptography.ECCurve]::CreateFromFriendlyName("nistP256")
    $ecdsa = [Security.Cryptography.ECDsa]::Create($curve)
    $pbe = [Security.Cryptography.PbeParameters]::new(
        [Security.Cryptography.PbeEncryptionAlgorithm]::Aes256Cbc,
        [Security.Cryptography.HashAlgorithmName]::SHA256,
        200000
    )
    $privatePem = $ecdsa.ExportEncryptedPkcs8PrivateKeyPem($plainPassword, $pbe)
    $parameters = $ecdsa.ExportParameters($false)
    if ($parameters.Q.X.Length -ne 32 -or $parameters.Q.Y.Length -ne 32) {
        throw "The generated public key is not an ECDSA P-256 key."
    }

    $keyDirectory = Split-Path -Parent $resolvedKeyPath
    New-Item -ItemType Directory -Path $keyDirectory -Force | Out-Null
    Set-Content -LiteralPath $resolvedKeyPath -Value $privatePem -Encoding UTF8 -NoNewline

    $formatBytes = {
        param([byte[]]$Bytes)
        ($Bytes | ForEach-Object { "0x{0:x2}" -f $_ }) -join ", "
    }
    $xBytes = & $formatBytes $parameters.Q.X
    $yBytes = & $formatBytes $parameters.Q.Y
    $header = @"
#pragma once

#include <array>
#include <cstdint>

namespace audio_share::updater {

// Generated by scripts/initialize-updater-key.ps1. The private key is not stored in the repository.
inline constexpr bool public_key_configured = true;
inline constexpr std::array<std::uint8_t, 32> public_key_x{ $xBytes };
inline constexpr std::array<std::uint8_t, 32> public_key_y{ $yBytes };

} // namespace audio_share::updater
"@
    Set-Content -LiteralPath $publicHeaderPath -Value $header -Encoding UTF8 -NoNewline

    $publicKeyBase64 = [Convert]::ToBase64String($ecdsa.ExportSubjectPublicKeyInfo())
    $androidPublicKey = @"
package io.github.mkckr0.audio_share_app.model

// Generated by scripts/initialize-updater-key.ps1. The private key is not stored in the repository.
object UpdatePublicKey {
    const val SPKI_BASE64 = "$publicKeyBase64"
}
"@
    Set-Content -LiteralPath $androidPublicKeyPath -Value $androidPublicKey -Encoding UTF8 -NoNewline

    Write-Host "Updater private key created: $resolvedKeyPath"
    Write-Host "Updater public key header updated: $publicHeaderPath"
    Write-Host "Android updater public key updated: $androidPublicKeyPath"
    Write-Host "Back up the private key and password securely. Losing either prevents existing clients from accepting future updates."
} finally {
    if ($ecdsa) {
        $ecdsa.Dispose()
    }
    $plainPassword = $null
    $plainConfirmation = $null
    if ($passwordPointer -ne [IntPtr]::Zero) {
        [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($passwordPointer)
    }
    if ($confirmationPointer -ne [IntPtr]::Zero) {
        [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($confirmationPointer)
    }
}
